apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-example-deployment
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec: 
      containers:
      - image: postgres
        name: postgres-container
        ports:
          - containerPort: 5432
        imagePullPolicy: Always
        env:
          - name: POSTGRES_PASSWORD
            value: "secret"
          
---

apiVersion: v1
kind: Service
metadata:
  name: database-example-svc
spec:
  type: ClusterIP
  ports:
  - name: "database"
    port: 5432
    protocol: TCP
  selector:
    app: database