apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-chat
  template:
    metadata:
      labels:
        app: go-chat
    spec:
      containers:
      - name: go-chat
        image: iqrashams/go-chat:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3333
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3333
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 3333
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-chat-service
spec:
  selector:
    app: go-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: NodePort